spring.application.name=apigateway

server.port=8080

# =========================
# JWT
# =========================
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# =========================
# Service URLs
# =========================
services.auth.url=${AUTH_SERVICE_URL:http://localhost:8081}
services.project.url=${PROJECT_SERVICE_URL:http://localhost:8082}

# =========================
# LOGGING
# =========================
logging.level.org.springframework.cloud.gateway=INFO
logging.level.reactor.netty.http.client=INFO