spring.application.name=apigateway

server.port=8080

# =========================
# JWT
# =========================
jwt.secret=${JWT_SECRET}

# =========================
# AUTH SERVICE ROUTE
# =========================
spring.cloud.gateway.routes[0].id=authservice
spring.cloud.gateway.routes[0].uri=${AUTH_SERVICE_URL}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**

# =========================
# PROJECT SERVICE ROUTE
# =========================
spring.cloud.gateway.routes[1].id=projectservice
spring.cloud.gateway.routes[1].uri=${PROJECT_SERVICE_URL}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/projects/**

# =========================
# LOGGING
# =========================
logging.level.org.springframework.cloud.gateway=INFO
logging.level.reactor.netty.http.client=INFO